### ISSUE TITLE
How to record certain scaler channels but not plot them?

### ISSUE THREAD

**Issue by prjemian** [APS-4ID-POLAR/ipython-polar#12]
Some combination of read_attrs and hints.  Need to better understand how hints work.

**Comment by prjemian** [comment]
Currently, does not record scaler channels that are not _selected_ (by `.select_channels()`).

**Comment by prjemian** [comment]
Note taking here:

`ophyd.ophydobj.Kind`: 

```python
class Kind(IntFlag):
    """
    This is used in the .kind attribute of all OphydObj (Signals, Devices).
    A Device examines its components' .kind atttribute to decide whether to
    traverse it in read(), read_configuration(), or neither. Additionally, if
    decides whether to include its name in `hints['fields']`.
    """
    omitted = 0b000
    normal = 0b001
    config = 0b010
    hinted = 0b101  # Notice that bool(hinted & normal) is True.
```

**Comment by prjemian** [comment]
Default is for `ophyd.ophydobj.OphydObject` is `Kind.normal`.

**Comment by prjemian** [comment]
Default for `ophyd.signal.Signal` is `Kind.hinted`.

**Comment by prjemian** [comment]
The BestEffortCallback handles hints [here](https://github.com/bluesky/bluesky/blob/bdf2cdd73b971e543459f9182ed1595e134c06d7/bluesky/callbacks/best_effort.py#L603-L618):

```
def hinted_fields(descriptor):
    # Figure out which columns to put in the table.
    obj_names = list(descriptor['object_keys'])
    # We will see if these objects hint at whether
    # a subset of their data keys ('fields') are interesting. If they
    # did, we'll use those. If these didn't, we know that the RunEngine
    # *always* records their complete list of fields, so we can use
    # them all unselectively.
    columns = []
    for obj_name in obj_names:
        try:
            fields = descriptor.get('hints', {}).get(obj_name, {})['fields']
        except KeyError:
            fields = descriptor['object_keys'][obj_name]
        columns.extend(fields)
    return columns
```

**Comment by prjemian** [comment]
Hints are described in the bluesky documentation on [callbacks](https://blueskyproject.io/bluesky/callbacks.html#hints).

**Comment by prjemian** [comment]
Also read here for example use: https://blueskyproject.io/bluesky/event_descriptors.html#hints

**Comment by prjemian** [comment]
This paragraph from callbacks documentation looks applicable here:

> A readable device might report many fields like `['chan1', 'chan2', 'chan3', 'chan4', 'chan5']` but perhaps only a couple are usually interesting. A useful hint might narrow them down to `{'fields': ['chan1', 'chan2']}` so that a “best-effort” plot does not display an overwhelming amount of information.

**Comment by gfabbris** [comment]
I tested this by just running the function:

```
for item in scalerd.channels.component_names: 
     channel = getattr(scalerd.channels,item) 
     if channel.chname.get() in ['Time','SCA1']: 
           channel.kind = 'hinted' 
     elif channel.chname.get() is '': 
           channel.kind = 'omitted' 
     else: 
           channel.kind = 'config' 
```

This does remove the extra channels from the plot, but it also doesn't save them. For the last `channel.kind` I also tried `omitted` (behaves the same as `config`), and  `normal` (same as `hinted`).

**Comment by gfabbris** [comment]
<img width="884" alt="Screen Shot 2020-09-03 at 11 57 51 AM" src="https://user-images.githubusercontent.com/10960331/92144701-b8f6ee00-eddc-11ea-818b-552b5db8d6af.png">

**Comment by gfabbris** [comment]
I realized that when we change the `kind` of each channel, both the `read_attrs` and `hints` get changed. I created a test `ScalerCH` as below and this works, but this allows for changing `hints`, so we may want to add some checks to be sure that it doesn't break anything.

```
class LocalScalerCH(ScalerCH):
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
        self._hints = {}
        
        fields = []
        for _, component in self._get_components_of_kind(Kind.normal):
            c_hints = component.hints
            fields.extend(c_hints.get('fields', []))
            
        self._hints = {'fields': fields}
    
    @property
    def hints(self):
        return self._hints

    @hints.setter
    def hints(self,values):
        self._hints = values
```

**Comment by gfabbris** [comment]
By the way, I tried to change the the line:

`for _, component in self._get_components_of_kind(Kind.normal):` 
to:
`for _, component in self._get_components_of_kind(Kind.hinted):`

but it didn't make a difference...

**Comment by gfabbris** [comment]
@prjemian could you review the [LocalScalerCH](https://github.com/APS-4ID-POLAR/ipython-polar/blob/298463956f3968e54a5ba3302c2baed24b448f7e/profile_bluesky/startup/instrument/devices/scaler.py#L19)?

**Comment by gfabbris** [comment]
No hurry

**Comment by gfabbris** [comment]
This is working well, closing this.
