### ISSUE TITLE
Why not make an energy device as a PvPositioner?

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#18]
Why not make an energy device as a PvPositioner?

_Originally posted by @prjemian in https://github.com/APS-4ID-POLAR/ipython-polar/pull/14#discussion_r475873905_

**Comment by gfabbris** [comment]
This is a great point. The problem here is that as we move energy, we may want the undulator and/or phase plates to also move, and I'm not sure how could this be handled as a PVPositioner. We could create a class that contain these three devices, but that might get messy. The other way I can think of would be to subscribe the undulator and phase retarder to the energy, but since these are different devices, I'm not that would well.

**Comment by prjemian** [comment]
Agreed.  Sounds more like a procedural operation involving multiple devices.  That is a plan.

**Comment by gfabbris** [comment]
Subscribing the undulator to the mono energy doesn't well within the RunEngine. Closing this.

**Comment by gfabbris** [comment]
Reopening because I really don't like the `moveE` plan. I think this is something that many beamlines will need and, on further thought, I think this could work:

1. It didn't work before is that I subscribed the undulator to the `mono.energy` readback, but it looks like it can be subscribed to the setpoint using `event_type=mono.energy.SUB_SETPOINT`.

2. But this will also mean that we will have to handle the undulator backlash within `undulator.downstream.energy.move`. This should be doable using a couple of status objects.

3. Phase retarders can also be subscribed to it, but we will probably need to add an `PRDeviceBase.energy` attribute that moves `PRDeviceBase.th`

**Comment by gfabbris** [comment]
Since we don't have access to the undulators, I tested this strategy in d450bce using the phase retarders. It works mostly well, but there are two unexpected behaviors:

1. It works if I use `%mov mono.energy _target`, but it does not work if I do `mono.energy.put(_target)`. Not sure why. It looks like the `mono.energy` subscription runs twice for some reason, and the phase retarder briefly starts to move, but then it stops.
2. This is supposed to make prevent the subscription to run right away: https://github.com/APS-4ID-POLAR/ipython-polar/blob/d450bceba2bc91536af2ec7353e8330c5d8d7d1a/profile_bluesky/startup/instrument/devices/phaseplates.py#L133 But it is still running it.

**Comment by gfabbris** [comment]
I just realized that it is unnecessary to have a `pr.energy` signal. Might be simpler to subscribe the `mono.energy` directly to `pr.th`.

**Comment by prjemian** [comment]
Agreed

**Comment by gfabbris** [comment]
The problems described above are fixed in eb2ab45. However, I realized one major problem: the action of moving the mono energy does not wait for the phase retarder to reach target. I haven't looked into this too much, but I don't see a way to easily handle a status object (that the RunEngine would see) within a subscription.

**Comment by gfabbris** [comment]
Changed `undulator.downstream.energy` to be a `PVPositioner` in dec85c7. Even without the subscription scheme, this (and the addition of the `pr.energy` pseudo motor) makes the `moveE` scan much cleaner!

The one issue is the undulator backlash. The `undulator.downstream.energy.move` should take care of it, but it has to wait for the first step to complete (move to target+backlash), so passing `wait=False` only applies to the second motion.

@prjemian: Should the backlash be handled by EPICS?

**Comment by prjemian** [comment]
I thought that backlash on energy moves was handled by the undulator EPICS support.  I'll ask Marty Smith to comment.

**Comment by gfabbris** [comment]
This is our current MEDM screen:

![Screen Shot 2021-01-04 at 12 51 05 PM](https://user-images.githubusercontent.com/10960331/103580556-088b1a80-4ea0-11eb-977d-5c181c7c19de.png)

**Comment by gfabbris** [comment]
As I understand, the current EPICS support at 4IDD does not handle backlash. This is how the undulator is moved in SPEC:

<img width="432" alt="Screen Shot 2021-01-04 at 3 13 23 PM" src="https://user-images.githubusercontent.com/10960331/103580635-2e182400-4ea0-11eb-86ca-8d3a4cf2b6bf.png">

**Comment by gfabbris** [comment]
What about making an `energy` `Signal` that is the beamline energy and moves all the devices needed? Just need to change the `energy.set` to move everything and return a stacked `AndStatus`.
