### ISSUE TITLE
Mono gets stuck when attempting to move to current energy

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#52]
Bluesky gets stuck if we try to move to the same energy as the current one. It's not clear to me what's happening. As I understand it, it wouldn't try to move if the `abs(current-target) < mono.energy.tolerance` (which is 0.0001 keV).

**Comment by gfabbris** [comment]
@prjemian: This indeed seem to be an issue with the EPICS support, it gets stuck in moving if you try to move to the same energy.

![kohzu](https://user-images.githubusercontent.com/10960331/102522133-77bcde00-405b-11eb-9652-56b5b466e823.gif)

**Comment by prjemian** [comment]
I'll relay this into the appropriate synApps module repository.
