### ISSUE TITLE
polartools?

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#56]
Should we create a "APS-4ID-POLAR/polartools"? I'm thinking that this could be an installable package with tools to load and process data. It'd be used both at the beamline and by users.

**Comment by strempfer** [comment]
Great suggestion!

**Comment by prjemian** [comment]
Great idea!  @gfabbris Can you create the new repo?  Message me if you need an assist.

**Comment by gfabbris** [comment]
@prjemian: should I use NSLS-II [cookiecutter](https://github.com/NSLS-II/scientific-python-cookiecutter)?
