### ISSUE TITLE
Use Github Actions for CI, not travis

### ISSUE THREAD

**Issue by prjemian** [APS-4ID-POLAR/ipython-polar#58]
The travis-ci web service that many repositories have used for continuous integration (unit testing) has changed its pricing model.  Only the most trivial use will be available for free in just a few weeks.

The repositories I use have transitioned (successfully) to use Github Actions.  Follow one such transition in this issue from apstools: https://github.com/BCDA-APS/apstools/issues/454.

**Comment by gfabbris** [comment]
I think this belongs to [polartools]( https://github.com/APS-4ID-POLAR/polartools)?

**Comment by prjemian** [comment]
You opened there, so I'm closing here.
