### ISSUE TITLE
Best way to create a "simulation-mode"

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#6]
I started playing with this by creating "sim_framework" and "sim_devices". Right now I just commented out the import calls in the collection.py, but we can create some conditions (like not being able to read from epics). With this, I could get it to run in my Mac.

@prjemian: Is this the best way to approach it? Creating simulated motors seem trivial based on a quick look at the bluesky tutorial, but it's not obvious to me how to create a simulated scaler.

**Comment by gfabbris** [comment]
by the way, this is done in my forked copy.

**Comment by prjemian** [comment]
I did not find a full scaler in the simulators.  Time to ask the DAMA 
team...

**Comment by gfabbris** [comment]
@prjemian: I tried the docker. The start_iocxxx.sh seems to run fine, I can access the container and see the ioc there. For instance "caget xxx:datetime" works fine if I run it within the container. But my the ioc is not visible to my computer, if I run "caget xxx:datetime", it says "Channel connect timed out: 'xxx:datetime' not found.". Any ideas?

**Comment by prjemian** [comment]
Are you starting the docker container with the [`--net=host`](https://github.com/prjemian/epics-docker/tree/master/n3_synApps#example-use) option?

**Comment by prjemian** [comment]
Example here: https://github.com/prjemian/epics-docker/tree/master/n3_synApps#example-use

**Comment by gfabbris** [comment]
It turns out docker in Mac does not support --net=host option (but it doesn't return any error if you try to use it). The only way to network with the container is through a port. I've tried using _-p 8000:8000_ when starting the container and _caget 127.0.0.1:8000:xxx:datetime_ but it doesn't work. Do you know if/how _caget_ would work through a port?

**Comment by gfabbris** [comment]
By the way: https://docs.docker.com/docker-for-mac/networking/

**Comment by prjemian** [comment]
EPICS ChannelAccess (CA) uses ports 5064 and 6065: `-p 5064:5064 -p 5065:5065`

**Comment by gfabbris** [comment]
What PV would pyepics see? The ones below didn't work...
![Screen Shot 2020-08-06 at 11 19 43 AM](https://user-images.githubusercontent.com/10960331/89556347-dda87780-d7d6-11ea-811e-434a4296ee2a.png)

**Comment by prjemian** [comment]
Any of the PVs from the IOC, such as: `xxx:datetime`, `xxx:UPTIME`, and `xxx:m1`.  These are all easy to type.  Maybe we need to tell the Mac that both tcp and UDP are permitted on those ports:

`-p 5064:5064/tcp -p 5065:5065/tcp -p 5064:5064/udp -p 5065:5065/udp`

or maybe use docker's bridged network instead:  `--net=bridge` (but that seems to be the default)

The first of these references is the most useful (but not sure any of them help):
* https://stackoverflow.com/questions/25170738/how-does-dockers-net-host-setting-work-and-how-can-i-do-something-similar-wi
* https://github.com/docker/for-mac/issues/68
* https://docs.docker.com/network/
* https://blog.codavel.com/docker-network-on-macos-how-to-reach-gigabit
* https://stackoverflow.com/questions/63092466/how-does-the-networking-work-between-macos-and-docker-linux-vm

**Comment by gfabbris** [comment]
It works! It needs (both): `-p 5064:5064/tcp -p 5064:5064/udp`

I don't know why, but using 5065 doesn't work (but it also doesn't hurt).

**Comment by prjemian** [comment]
One of them (5064) is the `EPICS_CA_SERVER_PORT` (see https://epics.anl.gov/base/R3-14/12-docs/CAref.html) that ChannelAccess listens for PV requests (does anyone have this PV name of "ssfhdsjdf"?)  Once an IOC is identified (you hope it is only one IOC), the server will create a separate channel (on a different port) to connect with _that_ PV.  The other (5065, `EPICS_CA_REPEATER_PORT`) receives CA information from various IOCs and routes it to the correct CA client on the workstation.  That's why 5065 seems to provide no particular value in this case.

**Comment by gfabbris** [comment]
This is working as discussed here. Closing this issue.
