### ISSUE TITLE
How to subscribe databroker.v2 to the RunEngine?

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#67]
@prjemian 

This line doesn't work with `db.v2`, because `insert` is not an attribute:

https://github.com/APS-4ID-POLAR/ipython-polar/blob/97c0b69a28310651312f5762f1eb806f696c9539/profile_bluesky/startup/instrument/framework/initialize.py#L59

````
In [12]: RE.subscribe(db.insert)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.conda/envs/bluesky_2021_1/lib/python3.8/site-packages/intake/catalog/base.py in __getattr__(self, item)
    338             try:
--> 339                 return self[item]  # triggers reload_on_change
    340             except KeyError:

~/.conda/envs/bluesky_2021_1/lib/python3.8/site-packages/intake/catalog/base.py in __getitem__(self, key)
    409             return out()
--> 410         raise KeyError(key)
    411 

KeyError: 'insert'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-12-3e447429dd7e> in <module>
----> 1 RE.subscribe(db.insert)

~/.conda/envs/bluesky_2021_1/lib/python3.8/site-packages/intake/catalog/base.py in __getattr__(self, item)
    339                 return self[item]  # triggers reload_on_change
    340             except KeyError:
--> 341                 raise AttributeError(item)
    342         raise AttributeError(item)
    343 

AttributeError: insert
````

**Comment by gfabbris** [comment]
It works if I do:
````
RE.subscribe(db.v1.insert)
````

But I guess there is a way to add the v2 databroker. I couldn't find it in either Bluesky or databroker manuals.

**Comment by prjemian** [comment]
I agree. It's time to learn the v2 way to do this.  I'll ask.

**Comment by gfabbris** [comment]
It looks like the default at NSLS2 is still loading through `.v1`:

https://github.com/NSLS-II/nslsii/blob/26ff4a10ff80540aa85a29aedbb508825f118af9/nslsii/__init__.py#L159

and:

https://github.com/bluesky/databroker/blob/30eb0c01e5a76352762b435f67223d77b1ce4a80/databroker/__init__.py#L7

**Comment by gfabbris** [comment]
Also, I think the *mongodb_config* file is different for `v2`:

https://blueskyproject.io/databroker/v2/administrator/index.html

**Comment by gfabbris** [comment]
@prjemian - as I understand from the discussion in slack, the current *recommended* way to do this is through v1, correct?

**Comment by prjemian** [comment]
Yes, that is correct. You can use a v2 catalog

db = databroker.catalog["mongodb_config"]

This is v2 but db.v1 is v1

Also, catalog can open Broker - style yml files
