### ISSUE TITLE
Mono setup

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#8]
It looks like that the apstools.devices.KohzuSeqCtl_Monochromator won't work because we don't want the mono to move the z and y motors. Is that correct @CrI3?

**Comment by prjemian** [comment]
There is a PV to freeze y1 and z2.  Three GUI shows what this PV is.  We
can add that to a local custom subclass or just set it in the GUI.  Better
we add that to a custom subclass so we can both ensure y1 and z2 are fixed
and document it in our data.

**Comment by gfabbris** [comment]
This was fixed by #14
